export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_WEATHER = 'FETCH_WEATHER';
export const CONVERT_TO_CELSIUS = 'CONVERT_TO_CELSIUS';
export const CONVERT_TO_FAHRENHEIT = 'CONVERT_TO_FAHRENHEIT';
